Add Circle configuration to build production branch

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,47 +1,62 @@
-version: 2
+# Use the latest 2.1 version of CircleCI pipeline process engine.
+# See: https://circleci.com/docs/2.0/configuration-reference
+version: 2.1
 
+# Define a job to be invoked later in a workflow.
+# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
 jobs:
-
-  wpcs:
-      docker:
-        - image: notnoopci/php:7.0-apache-node
-      steps:
-        - checkout
-        - run:
-            name: Install WPCS
-            command: |
-              sudo composer self-update
-              composer install
-        - run:
-            name: Run WPCS
-            command: vendor/bin/phpcs
-
-  lint:
+  build:
     docker:
-      - image: nickthegeek/gulp:latest
+      - image: cimg/php:8.0.26-node
     steps:
       - checkout
+      # Enable deploy ssh keys in order to get private submodules and push built branch back to GitHub.
+      - add_ssh_keys:
+          fingerprints:
+            - "dd:cc:38:91:e3:83:31:2d:f1:30:88:e5:03:2f:52:c6"
       - run:
-          name: NPM Install
-          command: |
-            cd themes/wmfoundation
-            npm install
+          name: Install composer dependencies
+          command: composer install
+      # This is copypasta from VIP's boilerplate; it will probably be removed soon.
       - run:
-          name: Gulp Lint
+          name: Create build directory
+          command: mkdir -p build
+      - run:
+          name: Create build readme
+          command: echo "This was built in CI on $(date)" > build/README.md
+      - run:
+          name: Add some helpful info to the README
           command: |
-            cd themes/wmfoundation
-            gulp lint
+            echo -e "\n\n## Continuous Integration & Continuous Deployment on VIP Go" >> build/README.md
+            echo -e "\nSee our docs in the [VIP Lobby](https://vip.wordpress.com/documentation/automated-build-and-deploy-on-vip-go/)" >> build/README.md
+            echo -e "\n\nThis branch e.g. master-built is created automatically when " >> build/README.md
+            echo "a commit or merge is made to the base branch e.g. master, using [your CircleCI configuration](../.circleci/config.yml), which you can **customize**" >> build/README.md
+      - run:
+          name: Test the build
+          command: |
+            if [ -f build/README.md ]; then
+              echo "Build succeeded";
+            else
+              echo "Build failed, file missing"; exit 1
+            fi
+      # Run the deploy: This will push the result to the {currentbranch}-built branch
+      - deploy:
+          name: Deploy -built branch to github
+          command: bash <(curl -s "https://raw.githubusercontent.com/Automattic/vip-go-build/master/deploy.sh")
 
-
+# Invoke jobs via workflows
+# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
 workflows:
-  version: 2
-  test_and_standards:
+  build-workflow:
     jobs:
-      - lint:
+      - build:
           filters:
             branches:
-              ignore: develop
-      - wpcs:
-          filters:
-            branches:
-              ignore: develop
+              only:
+                - production
+                - develop
+                - preprod
+              # Ensure job will never run on a branch with the `-built` suffix,
+              # to prevent endless loops of deploy scripts.
+              ignore:
+                - /^.*-built$/
