Implement basic CI workflow for Preprod environment, based on Sound Logo

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,22 +5,55 @@ version: 2.1
 # Define a job to be invoked later in a workflow.
 # See: https://circleci.com/docs/2.0/configuration-reference/#jobs
 jobs:
-  say-hello:
-    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
+  build:
     docker:
-      - image: cimg/base:stable
-    # Add steps to the job
-    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
+      - image: cimg/php:8.0.26-node
+    # Don't build from a branch with the `-built` suffix, to
+    # prevent endless loops of deploy scripts.
+    ignore:
+      - /^.*-built$/
     steps:
       - checkout
+      # Enable deploy ssh keys in order to get private submodules and push built branch back to GitHub.
+      - add_ssh_keys:
+          fingerprints:
+            - "a8:74:af:5b:26:3d:75:6d:37:f0:e8:a3:54:9d:91:e9"
       - run:
-          name: "Say hello"
-          command: "echo Hello, World!"
+          name: Install composer dependencies
+          command: composer install
+      # This is copypasta from VIP's boilerplate; it will probably be removed soon.
+      - run:
+          name: Create build readme
+          command: echo "This was built in CI on $(date)" > build/README.md
+      - run:
+          name: Add some helpful info to the README
+          command: |
+            echo -e "\n\n## Continuous Integration & Continuous Deployment on VIP Go" >> build/README.md
+            echo -e "\nSee our docs in the [VIP Lobby](https://vip.wordpress.com/documentation/automated-build-and-deploy-on-vip-go/)" >> build/README.md
+            echo -e "\n\nThis branch e.g. master-built is created automatically when " >> build/README.md
+            echo "a commit or merge is made to the base branch e.g. master, using [your CircleCI configuration](../.circleci/config.yml), which you can **customize**" >> build/README.md
+      - run:
+          name: Test the build
+          command: |
+            if [ -f build/README.md ]; then
+              echo "Build succeeded";
+            else
+              echo "Build failed, file missing"; exit 1
+            fi
+      # Run the deploy: This will push the result to the {currentbranch}-built branch
+      - deploy:
+          name: Deploy -built branch to github
+          command: bash <(curl -s "https://raw.githubusercontent.com/Automattic/vip-go-build/master/deploy.sh")
 
 # Invoke jobs via workflows
 # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
 workflows:
-  say-hello-workflow:
+  build_and_deploy:
     jobs:
-      - say-hello
+      - build:
+          filters:
+            branches:
+              only:
+                # - develop
+                - preprod
+                # - production
